#%RAML 1.0 Library

types:
  get_patient: !include data_types/patient.raml
  get_drugs: !include data_types/drug.raml
  post_patient: !include data_types/post_patient.raml
  post_measure: !include data_types/post_measure.raml
  post_prescription: !include data_types/post_prescription.raml
  get_prescription: !include data_types/prescription.raml
  get_measure: !include data_types/measure.raml
