#%RAML 1.0
title: Sample API

/resource:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "This is a dummy RAML that shoud be replaced with the actual API RAML."
              }
